### ISSUE TITLE
Compatible with other region?

### ISSUE THREAD

**Issue by flytomoon88** [tera-lab/tera-multiloader#2]
Hi,
I got error running and seems the folder path is not correct.

HKCU\\Software\\GameOn\\Pmang\\tera

is above the TERA game installation directory?
and can this mod be used in other region as well?
thanks!

**Comment by sarisia** [comment]
Hi there,

this mod is intended to be used in JP region and
we do not have plans to support other regions, so
if you want to use in other regions, feel free to fork
this repository and modify necessary parts
(not sure but change installed folder path in `index.js ` and
registry address in `reg.js` properly should work fine).
